local t = require "testing"
local Room = require "room.room"

t.describe("Room", function()
    t.it("creates with correct defaults", function()
        local r = Room.new(1, "lobby", 4)
        t.assert.eq(r.id, 1)
        t.assert.eq(r.name, "lobby")
        t.assert.eq(r.max_players, 4)
        t.assert.eq(#r.players, 0)
    end)

    t.it("add_player succeeds when not full", function()
        local r = Room.new(1, "lobby", 2)
        local ok, err = r:add_player({id = 10, name = "alice"})
        t.assert.truthy(ok)
        t.assert.falsy(err)
        t.assert.eq(#r.players, 1)
    end)

    t.it("add_player fails when full", function()
        local r = Room.new(1, "lobby", 1)
        r:add_player({id = 1, name = "a"})
        local ok, err = r:add_player({id = 2, name = "b"})
        t.assert.falsy(ok)
        t.assert.contains(err, "full")
    end)

    t.it("remove_player removes by id", function()
        local r = Room.new(1, "lobby", 4)
        r:add_player({id = 10, name = "alice"})
        r:add_player({id = 11, name = "bob"})
        r:remove_player(10)
        t.assert.eq(#r.players, 1)
        t.assert.eq(r.players[1].id, 11)
    end)

    t.it("get_player_ids returns list of ids", function()
        local r = Room.new(1, "lobby", 4)
        r:add_player({id = 5, name = "x"})
        r:add_player({id = 7, name = "y"})
        local ids = r:get_player_ids()
        table.sort(ids)
        t.assert.eq(ids[1], 5)
        t.assert.eq(ids[2], 7)
    end)

    t.it("is_empty returns true when no players", function()
        local r = Room.new(1, "lobby", 4)
        t.assert.truthy(r:is_empty())
        r:add_player({id = 1, name = "a"})
        t.assert.falsy(r:is_empty())
    end)

    t.it("to_info returns summary table", function()
        local r = Room.new(3, "arena", 8)
        r:add_player({id = 1, name = "a"})
        local info = r:to_info()
        t.assert.eq(info.id, 3)
        t.assert.eq(info.name, "arena")
        t.assert.eq(info.count, 1)
        t.assert.eq(info.max, 8)
    end)
end)
