local T = require("tools.test_runner")
local Utils = require("core.utils")

T.describe("Utils.gridToPixel", function()
    T.it("returns center of cell (1,1)", function()
        local x, y = Utils.gridToPixel(1, 1)
        T.assert_equal(x, Utils.OFFSET_X + 0.5 * Utils.CELL_SIZE)
        T.assert_equal(y, Utils.OFFSET_Y + 0.5 * Utils.CELL_SIZE)
    end)

    T.it("returns center of cell (8,8)", function()
        local x, y = Utils.gridToPixel(8, 8)
        T.assert_equal(x, Utils.OFFSET_X + 7.5 * Utils.CELL_SIZE)
        T.assert_equal(y, Utils.OFFSET_Y + 7.5 * Utils.CELL_SIZE)
    end)
end)

T.describe("Utils.pixelToGrid", function()
    T.it("converts center of cell (1,1) back correctly", function()
        local x, y = Utils.gridToPixel(1, 1)
        local row, col = Utils.pixelToGrid(x, y)
        T.assert_equal(row, 1)
        T.assert_equal(col, 1)
    end)

    T.it("converts center of cell (5,3) back correctly", function()
        local x, y = Utils.gridToPixel(5, 3)
        local row, col = Utils.pixelToGrid(x, y)
        T.assert_equal(row, 5)
        T.assert_equal(col, 3)
    end)

    T.it("returns nil for out-of-bounds pixel", function()
        local row, col = Utils.pixelToGrid(0, 0)
        T.assert_nil(row)
        T.assert_nil(col)
    end)

    T.it("returns nil for pixel below the grid", function()
        local row, col = Utils.pixelToGrid(300, 900)
        T.assert_nil(row)
    end)
end)

T.describe("Utils.lerp", function()
    T.it("returns start at t=0", function()
        T.assert_equal(Utils.lerp(10, 20, 0), 10)
    end)

    T.it("returns end at t=1", function()
        T.assert_equal(Utils.lerp(10, 20, 1), 20)
    end)

    T.it("returns midpoint at t=0.5", function()
        T.assert_equal(Utils.lerp(10, 20, 0.5), 15)
    end)
end)
